### ISSUE TITLE
Melhorias para o Fórum? 

### ISSUE THREAD

**Issue by renanbastos93** [braziljs/forum#11]
Prezados,

Gostaria de trazer uma sugestão para melhorar nosso fórum, então estava pensando e conversei com o @hnordt, e pensamos meio que junto em algumas coisas. Sendo elas:

#### Criação de Labels
 - artigo
 -  tópico-duplicado
 - duvida
 - discussão
 - feedback-request
 - portal
etc...
 
#### Criação de Categorias
 Aqui séria no Project criando áreas exemplo:
- React
- JQuery
- Angular
- JavaScript
- Conference
- Outros
etc...

#### Moderadores
Ter moderadores por áreas, ou seja, os tópicos ter um para react, outro para angular etc. Assim podendo haver uma administração melhor do nosso fórum e assim sempre auxiliando em deixar em ordem e auxiliando os demais no que for preciso.

Assim ilustrando essas informações aos demais, irá ser de grande auxilio.

Fico a disposição.

Att,
Renan Bastos

**Comment by alinebastos** [comment]
Oi, @renanbastos93, vou criar as labels agora, obrigada pela lembrança :)
Mas esse assunto sobre as melhorias do forum seria melhor em outro lugar, aqui o ideal é ser usado só para forum mesmo. Vamos conversar lá no slack sobre isso, pode ser?
Vou fechar esta issue.

**Comment by renanbastos93** [comment]
Como cada Label é uma identidade da issue, ou seja, uma característica, a parte de projetos seria pra dividir por categorias, entendeu?

**Comment by k30v1n** [comment]
Sim, isso eu sei. Mas oq quero dizer é que o sistema de projetos aqui nesse repositório acho que não faz muito sentido. Aquela aba faz mais sentido pra definir tarefas de um projeto, features, e tal.
Por exemplo, se resolvesse implementar um site do braziljs, cada módulo do site seria uma tarefa lá.

**Comment by tgremi** [comment]
Pessoal, gostaria de participar do Slack e poder contribuir com este projeto se possível, poderiam disponibilizar o o acesso?

**Comment by jaydson** [comment]
@tgremi o Slack é aberto, aqui o link (tá na home do portal BrazilJS): https://now-examples-slackin-vvjogtwzcf.now.sh/
