### ISSUE TITLE
Valor do Input

### ISSUE THREAD

**Issue by gustavo-silveira** [braziljs/forum#19]
Tenho esse componente

`<SmlsInputAirport
              id={airportOriginId}
              name='airport-origin'
              label='Aeropuerto de origen'
              airportData={this.state.airportData}
              airport={this.state.airportOriginId}
              onChange={this.handleFlifhghtOne}
              required
            />`

O meu estado está assim:

`this.state = {
      airportData: [],
      airportOriginId: '',
      airportDestination: '',
      }`

Chamado no onChange:

`  handleFlifhghtOne = () => {
    this.setState({ airportOriginId: this.props.value})
    console.log(this.props.value)
    console.log(this.props)
  }`

O problema que não consigo pegar o valor do input que no caso é um aeroporto.
Meu props está retornanod undefined

Como posso resolver isso ?

Obrigado

**Comment by felipenmoura** [comment]
teu problema está no `this`.
O props que teu this recebe vem "de um componente pai", não do valor dele.
O que tu pode fazer é usar o evento pra pegar este valor, algo tipo:

```js
handleFlifhghtOne = event => { this.setState({ airportOriginId: event.target.value});
```

**Comment by gustavo-silveira** [comment]
![image](https://user-images.githubusercontent.com/45269968/51497722-217d8c80-1dab-11e9-9e72-2e0dc6075b77.png)

Estou tomando esse erro, fazendo da forma que vc falou.... Não sei como resolver, se vc puder me ajudar eu agradeço.
Obrigado

**Comment by felipenmoura** [comment]
provavelmente o teu listener é o `onSuggestionSelect`, correto? Se sim, é ESTA função que receberá o `event`. Caso ela esteja chamando outras funções/métodos, ela precisa passar este evento adiante.
